---
title: "No Poverty - 1.1.1"
#author: "Fiona Spooner"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
    toc: true
geometry: margin=3cm
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 100, fig.align="center")
```


```{r, Libraries}
library(brolgar)
library(dplyr)
library(readr)
library(janitor)
library(tidyr)
library(rnaturalearth)
library(rnaturalearthdata)

source("~/Documents/ECEHH/SDG_Tracker/sdg_useful.R")

```

```{r}
no_pov <-
  read.csv("Data/SDG_1_1_1.csv", na = c("", "NA"), stringsAsFactors = FALSE) %>% clean_names()

kable(no_pov$nature) #shows how the data was collected:
```


```{r}
np <- no_pov %>%
  select(indicator,
         geo_area_name,
         time_period,
         value,
         x_age,
         x_sex,
         x_reporting_type) %>%
  mutate(iso_a3 = get_iso(geo_area_name)) %>% 
  filter(x_reporting_type == "G" & !is.na(iso_a3)) %>%  #removing estimated and modelled data
  select(-x_reporting_type) %>% 
  select(indicator, country = geo_area_name, iso_a3, year = time_period, value, age = x_age,
         sex = x_sex)


write.csv(np, "Output/ind_1_1_1_long.csv", row.names = FALSE)
```

```{r}
world <-
  janitor::clean_names(rnaturalearth::ne_countries(scale = "medium", returnclass = "sf"))

data_check <- world %>% 
                left_join(., most_recent, by = "iso_a3")
ggplot(data = data_check)+
  geom_sf(aes(fill = newest_data))+
  scale_fill_viridis_c(option = "plasma", trans = "sqrt")

```

Country groupings - Income Group

```{r}

ggplot(world)+
  geom_sf(aes(fill = income_grp))

```

Country groupings - Economy


```{r}

ggplot(world)+
  geom_sf(aes(fill = economy))

```
